AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DemoListS3BucketsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev

  DemoListS3BucketsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DemoListS3BucketsLambda
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 10
      Policies:
        - AmazonS3ReadOnlyAccess
      Events:
        DemoListS3BucketsApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DemoListS3BucketsApi
            Path: /
            Method: GET
  

  #THE FOLLOWING IS OPTIONAL
  # the above configures permissions automatically
  # but, if manual configuration is needed, we can add custom permissions as follows
  # following configures above lambda function to enable invoke permission for above api gateway  
  DemoListS3BucketsApiGatewayLambdaPermission:
    Type: "AWS::Lambda::Permission"    
    Properties: 
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt 
        - DemoListS3BucketsLambda
        - Arn    
      SourceArn: !Join [
        "", [
          "arn:aws:execute-api:", 
          {"Ref": "AWS::Region"}, ":", 
          {"Ref": "AWS::AccountId"}, ":", 
          !Ref DemoListS3BucketsApi, "/*/*/*"
          ]
        ] 